#pragma once
#include <sycl-sandbox/sandbox_api.h>
#include <string>
#include <vector>
#include <unordered_map>
#include <memory>
#include <filesystem>

struct KernelHandle {
    void*       handle     = nullptr;
    int         generation = 0;
    std::string name;
    std::string path;
    /// mtime of the source .so this handle was built from, used to skip
    /// redundant dlopen()'s when a scene switch reuses an already-active,
    /// unchanged kernel (see KernelLibrary::load()).
    std::filesystem::file_time_type src_mtime{};
};

class KernelLibrary {
public:
    /// @param build_dir  Root build directory containing the kernels/ subdirectory.
    /// @param native_suffix  Suffix appended to .so filename for native (non-SYCL)
    ///        kernels.  Empty by default (SYCL mode).  Set to "_native" in
    ///        software mode to load pure C++ kernel builds.
    KernelLibrary(std::string build_dir, const std::string &native_suffix = "");
    ~KernelLibrary();

    /// Load a kernel .so.  Returns nullptr if the binary doesn't exist.
    KernelHandle* load(const std::string& kernel_name);

    /// Rebuild kernel via cmake --build.  Returns true on success.
    bool          rebuild(const std::string& kernel_name);

    /// Unload a kernel handle.
    void          unload(KernelHandle* kh);

    /// Get the active handle for a kernel, or nullptr if not loaded.
    KernelHandle* active(const std::string& kernel_name) const;

    /// Return the CMake build target name for a kernel (includes native suffix).
    std::string build_target_name(const std::string &kernel_name) const {
        return kernel_name + native_suffix_;
    }

    /// Switch between SYCL and native kernel loading.
    /// @param use_native  true = load "_native" .so variants (CPU Software).
    void set_native_mode(bool use_native) {
        native_suffix_ = use_native ? "_native" : "";
    }

    /// Return the expected .so path for a kernel (may not exist).
    std::string so_path(const std::string &kernel_name) const;

    /// Return the build directory.
    const std::string& build_dir() const { return build_dir_; }

    /// Check whether the .so file for a kernel exists.
    bool so_exists(const std::string &kernel_name) const;

    /// Check whether a kernel binary is up-to-date relative to its
    /// source files by comparing timestamps.  Looks for dependency (.d)
    /// files generated by the compiler in CMakeFiles/<target>.dir/.
    /// Returns true if the .so is newer than all dependencies.
    bool is_up_to_date(const std::string &kernel_name) const;

    /// Add a kernel directory for dependency tracking.  The directory
    /// is scanned for .cpp/.h files to compare timestamps against.
    void add_kernel_source_dir(const std::string &kernel_name,
                               const std::string &source_dir);

    /// Source directory registered for a kernel (see
    /// add_kernel_source_dir), or "" if unknown.  Used by the profiler
    /// zone-name registry to scan a kernel's own sources for
    /// PROFILER_ZONE literals.
    std::string kernel_source_dir(const std::string &kernel_name) const {
        auto it = kernel_source_dirs_.find(kernel_name);
        return it != kernel_source_dirs_.end() ? it->second : "";
    }

private:
    std::string build_dir_;
    std::string native_suffix_; ///< e.g. "_native" for software kernels
    std::unordered_map<std::string, std::unique_ptr<KernelHandle>> handles_;
    std::unordered_map<std::string, KernelHandle*> active_;
    std::unordered_map<std::string, std::string> kernel_source_dirs_; ///< kernel → source dir
    int next_generation_ = 1;
};
